### ISSUE TITLE
Issue with public ECR since 0.2.21

### ISSUE THREAD

**Issue by gdlx** [oras-project/oras-py#167]
Since upgrading to 0.2.21+, I get the following error when trying to get some tags from a public ECR repo:

```python
from oras.client import OrasClient
client = OrasClient('public.ecr.aws')
client.get_tags('/aws-controllers-k8s/acm-chart')

Your Authorization Token is invalid.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "[...]/.venv/lib/python3.12/site-packages/oras/decorator.py", line 36, in __call__
    return self.func(cls, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[...]/.venv/lib/python3.12/site-packages/oras/provider.py", line 356, in get_tags
    self._do_paginated_request(tags_url, callable=extract_tags)
  File "[...]/.venv/lib/python3.12/site-packages/oras/provider.py", line 382, in _do_paginated_request
    self._check_200_response(response)
  File "[...]/.venv/lib/python3.12/site-packages/oras/provider.py", line 651, in _check_200_response
    raise ValueError(f"Issue with {response.request.url}: {response.reason}")
ValueError: Issue with https://public.ecr.aws/v2/aws-controllers-k8s/acm-chart/tags/list: Bad Request
```

When downgrading to 0.2.2:
```python
from oras.client import OrasClient
client = OrasClient('public.ecr.aws')
client.get_tags('/aws-controllers-k8s/acm-chart')

['0.0.13', '0.0.19', '0.0.20', 'v0.0.6', '0.0.4', '0.0.5', '0.0.11', '0.0.7', 'v0.0.4', '0.0.17', '0.0.16', 'v0.0.3', '0.0.6', 'v0.0.5', 'v0.0.1', '0.0.10', 'v0.0.2', '0.0.2', '0.0.8', '0.0.18', '0.0.3', '0.0.1', '0.0.15', '0.0.12', '0.0.9', '0.0.14']
```

I think it's caused by 81c4b04f7b1993602771946ef31f33a34a3e86e8.

Using the debugger, I've seen the sent authorization header has the value `Bearer None`, which isn't accepted by ECR.

With 0.2.2, no authorization header is sent, which is what's expected for an anonymous request.

**Comment by tarilabs** [comment]
Hi, am I correct to assume there is no entry in `~/.docker/config.json` for `public.ecr.aws` on the environment where this is found?

**Comment by gdlx** [comment]
There is not:
```
cat ~/.docker/config.json
{
        "auths": {},
        "currentContext": "buildx"
}
```

**Comment by tarilabs** [comment]
thanks, this way I have more element to ensure proper reproduction
